### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by momo54181** [azwhikaru/Action-OFRP-Builder#1]
![)@ X98GGD534YLBAOT(Y{}G](https://user-images.githubusercontent.com/79344479/236654285-d89ca1de-f2dc-4eab-ba59-371aea3e5caa.png)
我在编译的时候出现了错误
设备树：https://github.com/momo54181/android_device_mediatek_m7332

**Comment by zbieracz2000** [comment]
You have to include OmniROM common tree at vendor/omni/

Also, even if you did, there's an error in the workflow script, which clones the common tree into a wrong directory.  I created a pull request with a  #fix.
#2

**Comment by azwhikaru** [comment]
looks like it has been fixed
