### ISSUE TITLE
访问不存在的文件

### ISSUE THREAD

**Issue by jisuanjiQAQ** [azwhikaru/Action-OFRP-Builder#9]
运行 ls -al /home/runner/work/Action-OFRP-Builder/Action-OFRP-Builder/workspace/fox_11.0/out/target/product/
  ls -al /home/runner/work/Action-OFRP-Builder/Action-OFRP-Builder/workspace/fox_11.0/out/target/product/
  echo
  ls -al /home/runner/work/Action-OFRP-Builder/Action-OFRP-Builder/workspace/fox_11.0/out/target/product/OPPO R11S/
  shell: /usr/bin/bash -e {0}
ls：无法访问“/home/runner/work/Action-OFRP-Builder/Action-OFRP-Builder/workspace/fox_11.0/out/target/product/”：没有这样的文件或目录
错误：进程已完成，退出代码为 [2]

**Comment by azwhikaru** [comment]
![image](https://github.com/azwhikaru/Action-OFRP-Builder/assets/37921907/515849ae-6a09-4e9d-b252-9a2c77ae2e90)
